newrelic_license_key: {{ newrelic_license_key }}
newrelic_app_name: {{ impac_config.newrelic.common.app_name }}
REDIS_URL: redis://{{ impac.redis.endpoint }}:6379/0
SPARKPOST_API_KEY: {{ impac_config.sparkpost_api_key }}
PUSHER_APP_ID: {{ impac_config.pusher.app_id }}
PUSHER_KEY: {{ impac_config.pusher.key }}
PUSHER_SECRET: {{ impac_config.pusher.secret }}
SIDEKIQ_USERNAME: {{ impac_config.sidekiq.username }}
SIDEKIQ_PASSWORD: {{ impac_config.sidekiq.password }}
ROOT_KEY: {{ impac_config.root.api_key }}
ROOT_SECRET: {{ impac_config.root.api_secret }}
SECRET_KEY_BASE: {{ impac_config.secret_key_base }}
