---

- name: Impac | Setup deployment directories
  include: setup.yml

- name: Impac | Deploy new version
  include: deploy.yml
  tags: [deploy]

- name: Impac | Gathering EC2 facts
  action: ec2_facts
  tags: [deploy]

- name: Impac | Instance De-register
  ec2_elb:
    ec2_access_key: "{{ infra_ec2_aws_access_key }}"
    ec2_secret_key: "{{ infra_ec2_aws_access_secret }}"
    ec2_region: "{{ infra_ec2_aws_region }}"
    instance_id: "{{ ansible_ec2_instance_id }}"
    state: absent
  when: infra_ec2_aws_access_key is defined
  tags: [deploy]

- name: Impac | Run/Reload Puma Runtime (Debian)
  include: runtime_deb.yml
  tags: [deploy]
  when: ansible_os_family == "Debian"

- name: Impac | Run/Reload Puma Runtime (RHEL)
  include: runtime_rhel.yml
  tags: [deploy]
  when: ansible_os_family == "RedHat"

- name: Impac | Instance Register
  ec2_elb:
    ec2_access_key: "{{ infra_ec2_aws_access_key }}"
    ec2_secret_key: "{{ infra_ec2_aws_access_secret }}"
    ec2_region: "{{ infra_ec2_aws_region }}"
    instance_id: "{{ ansible_ec2_instance_id }}"
    ec2_elbs: "{{ item }}"
    wait: no
    state: present
  with_items: "{{ ec2_elbs }}"
  when: infra_ec2_aws_access_key is defined
  tags: [deploy]
