---
- name: Spark | Install Java (Debian)
  apt: "name={{ item }} state=present update_cache=yes"
  with_items:
    - openjdk-7-jdk
  when: ansible_os_family == "Debian"

- name: Spark | Create user account
  user: name={{ spark_user }}
        system=yes
        home=/home/spark
        shell={{ spark_user_shell }}
        state=present
        groups="{{ spark_user_groups | join(',') }}"
  tags: ["spark-user"]

- name: Spark | Ensure setup directories exist
  file: path="{{ item }}"
        owner={{ spark_user }}
        group={{ spark_user }}
        mode=0755
        state=directory
  with_items:
    - "{{ spark_log_dir }}"
    - "{{ spark_run_dir }}"

- name: Spark | Download distribution
  get_url: url="{{ spark_mirror }}/spark-{{ spark_version }}.tgz"
           dest="{{ spark_src_dir }}/spark-{{ spark_version }}.tgz"

- name: Spark | Extract distribution
  unarchive: src="{{ spark_src_dir }}/spark-{{ spark_version }}.tgz"
             dest="{{ spark_usr_parent_dir }}"
             copy=no
             creates="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}"

- name: Spark | Setup distribution symlinks
  file: src="{{ item.src }}"
        dest="{{ item.dest }}"
        state=link
  with_items:
    - { src: "{{ spark_usr_parent_dir }}/spark-{{ spark_version }}", dest: "{{ spark_lib_dir }}" }
    - { src: "{{ spark_usr_parent_dir }}/spark-{{ spark_version }}/conf", dest: "{{ spark_conf_dir }}" }
  tags: ["symlinks"]

- name: Spark | Create shims for binaries
  template: src=spark-shim.j2
            dest="/usr/bin/{{ item }}"
            mode=0755
  with_items:
    - spark-class
    - spark-shell
    - spark-sql
    - spark-submit
  tags: ["shims"]

- name: Spark | Setup configuration files
  template: src="conf/{{ item }}"
            dest="{{ spark_usr_parent_dir }}/spark-{{ spark_version }}/conf/{{ item }}"
  with_items:
    - spark-env.sh
    - spark-defaults.conf
  tags: ["config"]

- name: Spark | Add service scripts
  template: src="upstart/{{ item }}"
            dest="/etc/init/{{ item }}"
  with_items:
    - spark.conf
    - spark-slave.conf
  tags: ["service"]

- name: Spark | Start service
  service: name=spark state=started enabled=yes
  tags: ["service"]
