---

- name: MnoHub | Setup RDS instance
  include: rds.yml

- name: MnoHub | Setup deployment directories
  include: setup.yml

- name: MnoHub | Deploy new version
  include: deploy.yml
  tags: [deploy]

- name: MnoHub | Gathering EC2 facts
  action: ec2_facts
  tags: [deploy]

- name: MnoHub | Instance De-register
  ec2_elb:
    ec2_access_key: "{{ infra_ec2_aws_access_key }}"
    ec2_secret_key: "{{ infra_ec2_aws_access_secret }}"
    ec2_region: "{{ infra_ec2_aws_region }}"
    instance_id: "{{ ansible_ec2_instance_id }}"
    state: absent
  when: infra_ec2_aws_access_key is defined
  tags: [deploy]

- name: MnoHub | Run/Reload Puma/Sidekiq Runtime (Debian)
  include: runtime_deb.yml
  tags: [deploy]
  when: ansible_os_family == "Debian"

- name: MnoHub | Run/Reload Puma/Sidekiq Runtime (RHEL)
  include: runtime_rhel.yml
  tags: [deploy]
  when: ansible_os_family == "RedHat"

- name: MnoHub | Instance Register
  ec2_elb:
    ec2_access_key: "{{ infra_ec2_aws_access_key }}"
    ec2_secret_key: "{{ infra_ec2_aws_access_secret }}"
    ec2_region: "{{ infra_ec2_aws_region }}"
    instance_id: "{{ ansible_ec2_instance_id }}"
    ec2_elbs: "{{ item }}"
    wait: no
    state: present
  with_items: "{{ ec2_elbs }}"
  when: infra_ec2_aws_access_key is defined
  tags: [deploy]
