---

- name: Developer Platform | Install packages
  apt: "name={{ item }} state=present update_cache=yes"
  with_items:
    - python-mysqldb
  when: ansible_os_family == "Debian"

- name: Developer Platform | Install packages
  yum: "name={{ item }} state=present"
  with_items:
    - MySQL-python
  when: ansible_os_family == "RedHat"

- name: Developer Platform | Create RDS database
  mysql_db:
    login_host: "{{ dev_platform_config.database.hostname }}"
    login_user: "{{ rds.username }}"
    login_password: "{{ rds.password }}"
    login_port: 3306
    collation: utf8_general_ci
    encoding: utf8
    name: "{{ dev_platform_config.database.database }}"
    state: present

- name: Developer Platform | Create RDS database user
  mysql_user:
    login_host: "{{ dev_platform_config.database.hostname }}"
    login_user: "{{ rds.username }}"
    login_password: "{{ rds.password }}"
    login_port: 3306
    name: "{{ dev_platform_config.database.username }}"
    host: '%'
    password: "{{ dev_platform_config.database.password }}"
    priv: "{{ dev_platform_config.database.database }}.*:ALL,GRANT"
    state: present
