---

- name: Developer Platform | Add /etc/systemd/system/puma.service
  template: src=puma.service dest=/etc/systemd/system/puma.service force=yes mode=0755

- name: Developer Platform | Add /etc/systemd/system/sidekiq.service
  template: src=sidekiq.service dest=/etc/systemd/system/sidekiq.service force=yes mode=0755

- name: Developer Platform | Add puma to systemd
  service: name=puma state=restarted enabled=yes

- name: Developer Platform | Add sidekiq to systemd
  service: name=sidekiq state=restarted enabled=yes
