impac:
  # Must be a URL accessible by end users
  protocol: {{ impac_config.public_dns.scheme }}
  host: {{ impac_config.public_dns.host }}
  paths:
    root: /api/v1
    get_widget: /api/v1/get_widget
mno:
  protocol: {{ mnohub_config.public_dns.scheme }}
  host: {{ mnohub_config.public_dns.host }}
  private_protocol: {{ mnohub_config.private_dns.scheme }}
  private_host: {{ mnohub_config.private_dns.host }}
  paths:
    root: "/api/mnoe/v1"
tenant:
  id: {{ mnohub_config.default_tenant.id }}
  key: {{ mnohub_config.default_tenant.key }}

{% if frontend_config.frontend_hosts is defined %}
frontend_host:
{% for country in frontend_config.frontend_hosts %}
  {{ country }}: {{ frontend_config.frontend_hosts[country] }}
{% endfor %}
{% endif %}

{% if frontend_config.google_apps is defined %}
google_apps: {{ frontend_config.google_apps }}
{% endif %}

{% if frontend_config.aws_config is defined %}
aws_config: {{ frontend_config.aws_config }}
{% endif %}
