---

# Nex Configuration

- set_fact: maestrano_component="nex-app-server-local"

- name: Nex! | Create Redis Store
  elasticache:
    name: "{{ nex.redis.name }}"
    state: present
    engine: redis
    cache_port: "{{ nex.redis.cache_port }}"
    cache_engine_version: "{{ nex.redis.cache_engine_version }}"
    cache_parameter_group: "{{ nex.redis.cache_parameter_group }}"
    node_type: "{{ nex.redis.node_type }}"
    num_nodes: "{{ nex.redis.num_nodes }}"
    cache_subnet_group: "{{ redis_group.name }}"
    security_group_ids: "{{ redis_group.vpc_security_groups }}"
    region: "{{ aws_region }}"
    wait: yes
  when: not nex.redis.skip
  register: created_nex_redis

- name: Nex! | Add Redis Store DNS record
  route53:
    command: create
    zone: "{{ (route53.zone.name|string) }}"
    alias_hosted_zone_id: "{{ route53.zone.id }}"
    record: "{{ nex.redis.endpoint }}"
    type: CNAME
    value: "{{ created_nex_redis.elasticache.data.CacheNodes[0].Endpoint.Address }}"
    alias: False
    ttl: 60
    private_zone: "{{ route53.zone.private_zone }}"
  when: not nex.redis.skip

- name: Nex! | Create RDS subnets
  rds_subnet_group:
    name: "{{ environment_name }}-nex-rds-subnet"
    description: Subnet Group for Nex! RDS instance
    state: present
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    subnets: "{{ nex.rds.subnets }}"
  when: not nex.rds.skip
  register: rds_subnet_nex

- name: Nex! | Create RDS instance
  rds:
    command: create
    instance_name: "{{ nex.rds.name }}"
    db_engine: "{{ nex.rds.db_engine }}"
    size: "{{ nex.rds.size }}"
    instance_type: "{{ nex.rds.instance_type }}"
    multi_zone: "{{ nex.rds.multi_zone }}"
    subnet: "{{ environment_name }}-nex-rds-subnet"
    vpc_security_groups: "{{ nex.rds.vpc_security_groups }}"
    username: "{{ nex.rds.username }}"
    password: "{{ nex.rds.password }}"
    wait: yes
    wait_timeout: 2400
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    tags: "{{ nex.rds.tags }}"
  when: not nex.rds.skip
  register: rds_nex

- name: Nex! | Add DNS record
  route53:
    command: create
    zone: "{{ (route53.zone.name|string) }}"
    alias_hosted_zone_id: "{{ route53.zone.id }}"
    record: "{{ nex.rds.endpoint }}"
    type: CNAME
    value: "{{ rds_nex.instance.endpoint }}"
    alias: False
    ttl: 60
    private_zone: "{{ route53.zone.private_zone }}"
  when: not nex.rds.skip

- name: Nex! | Create Nex ELB
  ec2_elb_lb:
    name: "{{ nex.elastic_load_balancer.name }}"
    state: present
    scheme: "{{ nex.elastic_load_balancer.scheme | default('internet-facing')}}"
    connection_draining_timeout: "{{ nex.elastic_load_balancer.connection_draining_timeout }}"
    cross_az_load_balancing: "yes"
    region: "{{ aws_region }}"
    ec2_access_key: "{{ aws_access_key }}"
    ec2_secret_key: "{{ aws_secret_key }}"
    subnets: "{{ nex.elastic_load_balancer.subnets }}"
    security_group_ids: "{{ nex.elastic_load_balancer.security_group_ids }}"
    listeners: "{{ nex.elastic_load_balancer.listeners }}"
  when: not nex.elastic_load_balancer.skip
  register: nex_elastic_load_balancer

- name: Add DNS record for ELB
  route53:
    command: create
    zone: "{{ (route53.zone.name|string) }}"
    record: "{{ nex.dns_record.record }}"
    type: "{{ nex.dns_record.type }}"
    value: "{{ nex_elastic_load_balancer.elb.dns_name }}"
    alias: "{{ nex.dns_record.alias }}"
    ttl: "{{ nex.dns_record.ttl }}"
    private_zone: "{{ route53.zone.private_zone }}"
    alias_hosted_zone_id: "{{ nex.elastic_load_balancer.alias_hosted_zone_id }}"
    overwrite: "{{ nex.dns_record.overwrite }}"

- name: Create Nex! Launch Configuration
  ec2_lc:
    name: "{{ nex.launch_configuration.name }}"
    key_name: "{{ nex.launch_configuration.key_name }}"
    region: "{{ aws_region }}"
    ec2_access_key: "{{ aws_access_key }}"
    ec2_secret_key: "{{ aws_secret_key }}"
    image_id: "{{ nex.launch_configuration.image_id }}"
    instance_type: "{{ nex.launch_configuration.instance_type }}"
    security_groups: "{{ nex.launch_configuration.security_groups }}"
    user_data: "{{ lookup('template', '../templates/user_data.sh') }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 50
        device_type: gp2 # SSD
        delete_on_termination: true
  when: not nex.launch_configuration.skip

- name: Create Nex! Auto Scaling Group
  ec2_asg:
    name: "{{ nex.auto_scaling_group.name }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    launch_config_name: "{{ nex.launch_configuration.name }}"
    min_size: "{{ nex.auto_scaling_group.min_size }}"
    max_size: "{{ nex.auto_scaling_group.max_size }}"
    desired_capacity: "{{ nex.auto_scaling_group.desired_capacity }}"
    vpc_zone_identifier: "{{ nex.auto_scaling_group.vpc_zone_identifier }}"
    availability_zones: "{{ nex.auto_scaling_group.availability_zones }}"
    load_balancers: "{{ nex.elastic_load_balancer.name }}"
    tags: "{{ nex.auto_scaling_group.tags }}"
  when: not nex.auto_scaling_group.skip
  register: nex_auto_scaling_group
