---

deploy_directory: /apps/mnohub
default_environment:
  RAILS_ENV: "{{ rails_environment }}"
  JAVA: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  PATH: /opt/jruby/current/bin:{{ ansible_env.PATH }}

mnohub_config:
  puma_worker_threads: 128
  sidekiq_worker_threads: 25
  java_opts:
    xms: "{{ (0.50 * ansible_memtotal_mb)|int }}m"
    xmx: "{{ (0.50 * ansible_memtotal_mb)|int }}m"
    max_perm_size: 512m
