---

# For RedHat only
sumocollector_installer_rpm: "https://collectors.sumologic.com/rest/download/rpm/64"
sumologic_installer_rpm_local_folder: "/tmp"

# For Debian apt installation only
sumologic_installer_remote_file: "/tmp/sumocollector.deb"
sumocollector_installer_download: "https://collectors.sumologic.com/rest/download/deb/64"

# Credentials
sumologic_collector_accessid: ""
sumologic_collector_accesskey: ""

# Allow overwrite of old collectors. See:
#   https://service.sumologic.com/help/Default.htm#Using_Clobber.htm
sumologic_collector_clobber: ""

sumologic_host_name: "{{ ansible_hostname }}"
sumologic_installer_file: ""
sumologic_collector_source_template: "collector.json.j2"
sumologic_collector_timezone: "UTC"
sumologic_collector_force_timezone: "false"
sumologic_collector_default_log_path:
  - name: "Sys Log"
    path: "/var/log/syslog"
    use_multiline: false
    category: "OS/Linux/Syslog"
