---

- name: Configure Nex instances
  hosts: localhost
  connection: local
  vars_files:
  - [ "vars/{{ env_config }}.yml" ]
  - [ "vars/{{ env_config }}_secrets.yml" ]
  roles:
    - role: common
    - role: ntp
    - { role: swapfile, swapfile_swappiness: 10 }
    - { role: newrelic, when: not((newrelic_license_key is undefined) or (newrelic_license_key is none)) }
    - { role: rvm_io.rvm1-ruby, tags: ruby, rvm1_rubies: ['ruby-2.3.1'] }
    - { role: jdauphant.nginx, keep_only_specified: true }
    - { role: sumocollector, sumologic_collector_application_log_path: "{{ sumologic.nex.log_path }}", sumologic_host_name: "core-nex-{{ rails_environment }}", when: not(sumologic.skip) }
    - { role: splunk }
    - { role: nex }
    - { role: logrotate, logrotate_scripts: [{name: nex, path: "{{ deploy_directory }}/shared/log/*.log", options: "{{ logrotate.options }}"}] }
