# {{ ansible_managed }}

newrelic_license_key: {{ newrelic_license_key }}
{% if connec_config.component is defined and connec_config.component == 'api' %}
newrelic_app_name: {{ connec_config.new_relic.app_name }} API
{% endif %}
{% if connec_config.component is defined and connec_config.component == 'jobs' %}
newrelic_app_name: {{ connec_config.new_relic.app_name }} Jobs
{% endif %}

REDIS_URL: redis://{{ connec.redis.endpoint }}:6379/0

SIDEKIQ_USERNAME: {{ connec_config.sidekiq.admin.username }}
SIDEKIQ_PASSWORD: {{ connec_config.sidekiq.admin.password }}
SIDEKIQ_SYNC_JOB: {{ connec_config.sidekiq.limits.sync_job }}
SIDEKIQ_DEMO_DATA_JOB: {{ connec_config.sidekiq.limits.demo_data }}
SYNC_JOB_BATCHES: {{ connec_config.sidekiq.sync_job_batches }}

FORCE_SSL: {{ connec_config.force_ssl }}

OPENEXCHANGERATES_APP_ID: {{ mnohub_config.secrets.open_exchange_rate_id }}

XROV2_PARALLEL_THREADS: {{ connec_config.xrov2_parallel_threads }}

MNO_ROOT_KEY: {{ connec_config.root.api_key }}
MNO_ROOT_SECRET: {{ connec_config.root.api_secret }}

CACHE_DISABLED: {{ connec_config.cache_disabled }}
FX_DISABLED: {{ connec_config.fx_disabled }}
